### PR TITLE
Document pv configuration in k8s-docker-for-mac

### PR DESCRIPTION
**Pull request by daisy-ycguo**
Resolves issue #374

### CODE REVIEW

**Comment by dgrove-oss** [comment]
I don't believe this change is correct.  I am using docker-for-desktop routinely with dynamic provisioning of volumes and I don't need to do either of these things.

**Comment by dgrove-oss** [comment]
but, i am running docker 2.0.0.0-mac78.  So perhaps it is a new feature that isn't present in 18.06.  Daisy, could you confirm what version of docker you have on your machine?

**Comment by dgrove-oss** [comment]
limited version to 18.06  in #377

**Comment by daisy-ycguo** [comment]
I'm using version 18.06.1-ce-mac73 (26764), a little bit old version.

**Pull request merged**
