### PR TITLE
REVIEW: update Travis scripts to conform to other repos. and add scancode.

### PR DESCRIPTION
**Pull request by mrutkows**

### CODE REVIEW

**Comment by DanLavine** [comment]
Odd. Cannot comment on a file location change, but the build script needs to update the location of ROOTDIR for file locations.

There is also the invoker [PR](https://github.com/apache/incubator-openwhisk-deploy-kube/pull/34) which has a number of changes for the build script. Not sure which one will be merged first, but one of the PRs will need to be rebased onto master.

**Comment by ddragosd** [comment]
It doesn't seem like the build failure is caused by these changes, isn't it ?

I'm seeing in the build logs: 

```
kubectl get pods --all-namespaces -o wide --show-all
NAMESPACE     NAME                        READY     STATUS    RESTARTS   AGE       IP           NODE
kube-system   kube-dns-2185667875-7rbzk   4/4       Running   0          13m       172.17.0.2   127.0.0.1
+echo 'The job to configure OpenWhisk did not finish with an exit code of 1'
The job to configure OpenWhisk did not finish with an exit code of 1
+exit 1
The command "./tools/travis/build.sh" exited with 1.
```

**Comment by mrutkows** [comment]
@dragos No, the failure is well past scancode utility running, which if you look in the Travis logs it says "all checks passed" just fine from scancode.  The error happens well after.

**Comment by houshengbo** [comment]
This PR needs a rebase, since there is a conflict.

**Comment by mrutkows** [comment]
@ddragosd started over in: https://github.com/apache/incubator-openwhisk-deploy-kube/pull/49

**Pull request closed without merging**
