### PR TITLE
Update runtimes for upstream changes.

### PR DESCRIPTION
**Pull request by rabbah**
Updated runtimes.json per https://github.com/apache/incubator-openwhisk/pull/3680.

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Do we need the same changes to `runtimes-minimal-travis.json` ?

**Comment by rabbah** [comment]
oy.

**Comment by dgrove-oss** [comment]
Something additional needs to be fixed in invoker configuration, I pulled the invoker logs from one of the failing runs, and I see
```

[2018-06-18T19:58:06.884Z] [ERROR] [#tid_sid_invokerHealth] [DockerClientWithFileAccess] code: 125 , stdout: , stderr: Unable to find image 'nodejs6action:latest' locally
/usr/bin/docker: Error response from daemon: pull access denied for nodejs6action, repository does not exist or may require 'docker login'.
See '/usr/bin/docker run --help'. [marker:invoker_docker.run_error:67883:604]
```

**Comment by rabbah** [comment]
I don't think my PR was complete - this playbook needs adjustments:

https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docker/docker-pull/pull_images.yml

**Comment by dgrove-oss** [comment]
follow up changes in #233

**Pull request merged**
