### PR TITLE
Add Redis and ApiGateway deployments

### PR DESCRIPTION
**Pull request by DanLavine**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
worked for me.

**Comment by csantanapr** [comment]
Hey @dgrove-oss can you submit a new PR solving the conflict on this one?

**Comment by dgrove-oss** [comment]
passing the buck to @DanLavine

**Comment by DanLavine** [comment]
Not sure why CI failed here. It passed on my branch for this PR https://travis-ci.org/DanLavine/incubator-openwhisk-deploy-kube/builds/275609677

**Comment by dgrove-oss** [comment]
it worked for me as well.  Maybe rebase to master & force push to cause travis to run again?

**Comment by bbrowning** [comment]
Anyone with write access can just restart the Travis build from the Travis UI without having to push a new commit.

**Comment by rabbah** [comment]
restarted - you should be able to do that yourself though if you oauth with travis... no?

**Comment by dgrove-oss** [comment]
thanks. I don't have write access yet.

**Comment by bbrowning** [comment]
Travis failed again, this time with an issue I fixed regarding the .travis.yml in that got merged in #58. You'll have to rebase on top of that to get that fix in.

**Comment by dgrove-oss** [comment]
@DanLavine do you have time to rebase again to pick up #58 or do you want me to do it?  Either is fine.

**Comment by DanLavine** [comment]
I can quickly rebase this so it has all the latest changes

**Comment by dgrove-oss** [comment]
@rabbah rebased the PR.  Now just needs to be merged.

**Pull request merged**
