### PR TITLE
Add Helm chart support for replicated Kafka instances

### LINKED ISSUE #354: enable replicated kafka pods
For production deployments, the kakfa StatefulSet should have a replicaCount > 1.

To enable this, we need to do similar changes as we did to enable replicated zookeeper.
  1. Change the PVC to a PVCTemplate
  2. Need a kakfa-connect macro in _helpers so that clients can be told about the multiple kafka brokers they should connect to.

### PR DESCRIPTION
**Pull request by dgrove-oss**
Fixes #354.

### CODE REVIEW

**Comment by sciabarracom** [comment]
I was trying to install it but I do not see documentation how to use a replicated Kafka

**Comment by dgrove-oss** [comment]
You simply set `kafka.numReplicas` to a value bigger than 1 and the chart does everything else.

**Comment by sciabarracom** [comment]
I was a able to use the chart in an internal cluster, without tls, with kafka replicaCount=3 and create a simple hello application with wsk -i. However, if I run helm test I get:

```
helm test owdev
RUNNING: owdev-tests-package-checker
FAILED: owdev-tests-package-checker, run `kubectl logs owdev-tests-package-checker --namespace openwhisk` for more info
RUNNING: owdev-tests-smoketest
FAILED: owdev-tests-smoketest, run `kubectl logs owdev-tests-smoketest --namespace openwhisk` for more info
```

Logs say:
```
kubectl logs owdev-tests-package-checker --namespace openwhisk
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to https://192.168.64.8:31001
Looking for package combinators
wsk package list did not find combinators; sleep 5 seconds and try again
wsk package list did not find combinators; sleep 5 seconds and try again
wsk package list did not find combinators; sleep 5 seconds and try again
wsk package list did not find combinators; sleep 5 seconds and try again
wsk package list did not find combinators; sleep 5 seconds and try again
FAILED! Could not list package combinators
```
kubectl logs owdev-tests-smoketest --namespace openwhisk
```
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to https://192.168.64.8:31001
Creating action
error: Unable to create action 'hello': resource already exists (code trdixQTHS2QKGQuYtPSpQLsB1BgKo74P)
Run 'wsk --help' for usage.
FAILED! Could not create a hello action!
Listing action
success: wsk action list included hello
Inoking action via CLI
Invoking as web action
Registering as an api
error: Unable to create API: The requested resource does not exist. (code GdKpKNBSxjUk2sZHUq0Edg92FDw1IDrM)
FAILED: unable to create API
Invoking action via the api
error: Unable to obtain the API list: The requested resource does not exist. (code ucrwaMLTXoFq8N6bA1KKzdxjwMaZKHD7)
FAILED! Could not invoke hello via apigateway
```

**Comment by sciabarracom** [comment]
I notices also that while I have 3 Kafka, there is only one zookeeper that is a SPF. Should I set zookeeper replicaCount to 3 too?

**Comment by dgrove-oss** [comment]
Hi.  Setting zookeeper.replicaCount to 3 is expected to work (and will eliminate zookeeper as a SPF).  It should be possible to test the kafka with 3 replicas with only 1 zookeeper though.  Both work for my on an IBM IKS cluster.

Based on the Helm test failure, I suspect that your install-package job failed.  It looks like that the apiMgmt actions are missing and the combinator package was not installed.  One way for this to happen is if your ingress is misconfigured (is https://192.168.64.8:31001 actually a valid api_host if you don't have tls configured). Try `kubectl logs jobs/owdev-install-packages -n openwhisk` to see if the packages actually got installed.

Thanks for continuing to try to test this; I appreciate it.

**Comment by sciabarracom** [comment]
I intend to make this work :) I am using an internal cluster (not single node)  built with multipass, so I cannot have tls configured (there are no public ips). Is it possible to install in a similar setup? I guessed it is - I mixed the configuration for  Docker Desktop with the configuration for a generic Kubernetes cluster. This is my configuration please suggest a better one if it is wrong:

```
whisk:
  ingress:
    type: NodePort
    apiHostName: 192.168.64.8
    apiHostPort: 31001
nginx:
    httpsNodePort: 31001
kafka:
   replicaCount: 3
```

**Comment by sciabarracom** [comment]
When I try to deploy the first time install packages fails, it works if I drop and redeploy. It would be helpful if when the install package  fails the jobs does not disappear.

**Comment by dgrove-oss** [comment]
#457 might help.  The first time one deploys in a cluster it could take a very long time for the invoker init container that pulls all the runtime images to complete.  We should not timeout the install-packages job while that could still be running.

**Pull request merged**
