### PR TITLE
Improvement in default chart values and make #251 work by just pulling the chart

### PR DESCRIPTION
**Pull request by cduque89**
We have been working in a way to easily deploy the chart out of the box in our k8s installed on Google Cloud.

After pulling the current master branch we felt under #251 problem. With the current values files it is possible to avoid that problem.

We also make a generic ingress.yaml that should work for both nginx ingress and the current ibm ingress that you have. Please review the changes to it and to ingress.md to guarantee everything is fine.

### CODE REVIEW

**Comment by dgrove-oss** [comment]
This looks really nice!  Thanks for doing this.

Could you please sign an Apache CLA (see https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md)?  Once you have done this, I'd be happy to merge this PR.

**Comment by cduque89** [comment]
Just did my submission. Do you know how long does it usually takes?

**Comment by dgrove-oss** [comment]
Thanks for doing the CLA. Usually it is pretty fast (within 24 hours).

**Comment by cduque89** [comment]
Hi @dgrove-oss just got the confirmation e-mail.

The relevant part is:

"Dear Carlos Duque,

This message acknowledges receipt of your ICLA, which has been filed in the Apache Software Foundation records.

If you have been invited as a committer, please advise the (P)PMC that your ICLA has been filed."

Let me know if everything else is needed 👍

**Comment by cduque89** [comment]
Cool hope this helps someone in the future 👍

**Pull request merged**
