### PR TITLE
Adopt latest scancode ASF release config. (enforce *.md, .conf, .sh).

### PR DESCRIPTION
**Pull request by mrutkows**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
```
Scan detected 2 error(s) in 2 file(s):
  [/home/travis/build/apache/incubator-openwhisk-deploy-kube/tools/travis/../../README.md]:
       1: file does not include required license header.
  [/home/travis/build/apache/incubator-openwhisk-deploy-kube/tools/travis/../../get_helm.sh]:
       1: file does not include required license header.
```

**Comment by mrutkows** [comment]
@dgrove-oss just saw same in travis logs, thought I updated my fork before the push

**Comment by mrutkows** [comment]
@dgrove-oss apparently the openwhisk CLI repo's README.md is overwriting this project's README.md (and it is not compliant with the new ASF headers (I will fix that .... tomorrow).  However, you may want to correct his side-effect (file overwrite) as scancode is supposed to test compliance of files in this repo.

**Comment by dgrove-oss** [comment]
ok.  I'll do something similar to the gethelm fix you just merged for me and have setup.sh do all of its gets in /tmp instead of in the top dir.

**Comment by csantanapr** [comment]
The scancode step should be done much earlier on the pure git repo source

**Comment by mrutkows** [comment]
@csantanapr likely we should be doing less in setup.sh (i.e., during the "before_install" phase).  Typically, we place scancode as the first step under the (build) "script" step, once all the code is laid out/marshalled/extracted, etc.  In any event, we should have separation of dependencies/tools that are laid down (not unzip/untar) directly under home) which Dave has been making sure of with push/pop.

**Comment by dgrove-oss** [comment]
@mrutkows try rebasing again when you get a chance.  I believe setup.sh shouldn't touch the cloned repo now.

**Comment by mrutkows** [comment]
@dgrove-oss thanks Dave!

**Pull request merged**
